version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: marketai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
      - "50051:50051"

  cards-service:
    build:
      context: .
      dockerfile: Dockerfile.cards
    container_name: cards-service
    restart: always
    depends_on:
      - postgres
      - auth-service
    ports:
      - "8081:8081"
      - "50052:50052"


volumes:
  pgdata:
