version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: marketai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    restart: always
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_DB_NAME: marketai
      POSTGRES_DB_USER: postgres
      POSTGRES_DB_PASSWORD: password
    ports:
      - "8080:8080"
      - "50051:50051"

  cards-service:
    build:
      context: .
      dockerfile: Dockerfile.cards
    container_name: cards-service
    restart: always
    depends_on:
      - postgres
      - auth-service
    environment:
      CARDS_HTTP_PORT: "8081"
      CARDS_POSTGRES_HOST: postgres
      CARDS_POSTGRES_PORT: "5432"
      CARDS_POSTGRES_DB_NAME: marketai_cards
      CARDS_POSTGRES_DB_USER: postgres
      CARDS_POSTGRES_DB_PASSWORD: password
      AUTH_GRPC_ENDPOINT: auth-service:50051
    ports:
      - "8081:8081"
      - "50052:50052"

  frontend:
    build:
      context: ./marketai-front
      args:
        VITE_API_URL: http://localhost:8080
        VITE_CARDS_API_URL: http://localhost:8081
    container_name: frontend
    restart: always
    depends_on:
      - auth-service
      - cards-service
    ports:
      - "3000:80"

volumes:
  pgdata:
