http:
  port: ${CARDS_HTTP_PORT}
  apiBasePath: "/cards/api/v1"
  readTimeout: 15s
  writeTimeout: 0s
  bodyLimitSkipPaths: []
logger:
  level: debug
  serviceName: cardsdb
probes:
  port: ":8061"
  livenessPath: "/healthz"
  readinessPath: "/readyz"
  prometheusPath: "/metrics"
  checkIntervalSeconds: 10
postgres:
  host: ${CARDS_POSTGRES_HOST}
  port: ${CARDS_POSTGRES_PORT}
  dbName: ${CARDS_POSTGRES_DB_NAME}
  sslMode: "disable"
  maxConn: 10
  minConn: 2
  healthCheckPeriodSeconds: 30
  maxConnIdleTimeSeconds: 60
  maxConnLifetimeSeconds: 300
tracing:
  enabled: false
  endpoint: ""
  sampleRatio: 1.0
grpc:
  port: 50052
auth:
  grpc_endpoint: "localhost:50051"

ai:
  openai_api_key: ${OPENAI_API_KEY}
  model: "gpt-4.5"