http:
  port: ":8090"
  apiBasePath: "/cards/api/v1"
  readTimeout: 15s
  writeTimeout: 0s
  bodyLimitSkipPaths: []
logger:
  level: debug
  serviceName: cardsdb
probes:
  port: ":8061"
  livenessPath: "/healthz"
  readinessPath: "/readyz"
  prometheusPath: "/metrics"
  checkIntervalSeconds: 10
postgres:
  host: "tramway.proxy.rlwy.net"
  port: 18941
  dbName: railway
  sslMode: "disable"
  maxConn: 10
  minConn: 2
  healthCheckPeriodSeconds: 30
  maxConnIdleTimeSeconds: 60
  maxConnLifetimeSeconds: 300
tracing:
  enabled: false
  endpoint: ""
  sampleRatio: 1.0
grpc:
  port: 50052
auth:
  grpc_endpoint: "localhost:50051"
ai:
  deepseek_api: ${DEEPSEEK_API_KEY}
  model: "deepseek-chat"