http:
  port: ${HTTP_PORT}
  apiBasePath: "/auth/api/v1"
  readTimeout: 15s
  writeTimeout: 0s
  bodyLimitSkipPaths: []
logger:
  level: debug
  serviceName: authdb
probes:
  port: ":8060"
  livenessPath: "/healthz"
  readinessPath: "/readyz"
  prometheusPath: "/metrics"
  checkIntervalSeconds: 10
grpc:
  port: ${GRPC_SERVER_PORT}
postgres:
  host: ${POSTGRES_HOST}
  port: ${POSTGRES_PORT}
  dbName: ${POSTGRES_DB_NAME}
  sslMode: "disable"
  maxConn: 10
  minConn: 2
  healthCheckPeriodSeconds: 30
  maxConnIdleTimeSeconds: 60
  maxConnLifetimeSeconds: 300
tracing:
  enabled: false
  endpoint: ""
  sampleRatio: 1.0

# JWT секрет для всех сервисов
jwt_secret: ${JWT_SECRET}